version: '2.2'
services:
  php:
    environment:
      - 'XDEBUG_CONFIG=idekey=symfony-vuejs remote_host=${HOST_IP}'
      - 'PHP_IDE_CONFIG=serverName=symfony-vuejs'
  web:
    networks:
      - default
      - reverse-proxy
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:api.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=80
    environment:
      - 'VIRTUAL_HOST=api.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - VIRTUAL_PORT=80
  node:
    networks:
      - default
      - reverse-proxy
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=8080
    environment:
      - 'VIRTUAL_HOST=${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - VIRTUAL_PORT=8080
  db:
    ports:
      - '${DOCKER_DEVBOX_PORT_PREFIX}32:5432'
  mailcatcher:
    build:
      context: .docker
      dockerfile: mailcatcher/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/mailcatcher'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    networks:
      - default
      - reverse-proxy
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:mailcatcher.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=80
    environment:
      - 'VIRTUAL_HOST=mailcatcher.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - VIRTUAL_PORT=80
networks:
  reverse-proxy:
    name: '${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}'
    external: true
